# Build settings
theme: minima
plugins:
  # - jekyll-feed
  - jekyll-sitemap


# Optional configuration options

title: Heroes of Might and Magic in Memories
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Heroes of Might and Magic is a Mythologic and Strategic video game develop by New World Computing and 3D0 in 1999.
url: "https://github.com/StaticWebSiteTremplateTrialOne/StaticWebSiteTremplateTrialOne.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author: Paul MICHAUX
github_username:  77Michaux

# feed path
# feed: 
  # path: /feed.xml

# Optional front matter
image: img/HOMMIII.jpg

# Enable or Disable jekyll-feed
# feed:
  # disable_in_development: true







